### ISSUE TITLE
[Bug]: tar linux toolchain has no hermetic glibc

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/bazel-lib#621] opened 2023-10-11 18:31 UTC
### What happened?

bsdtar linux toolchain doesn't fetch glibc, instead relies on a really specific version of glibc which might not work on some distros.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by alexeagle** [comment] 2023-10-31 21:37
dupe of #615

**Closed by alexeagle** 2023-10-31 21:37 UTC
Labels: bug, funding needed
